checkpatch: Error if signal(2) is used non-portably.
The only portable use for signal(2) is setting a signal to SIG_IGN or
SIG_DFL.  Everything else is a portability minefield.  This change
adds such a check to checkpatch.  It gives an error like this:

  ERROR: Use sigaction instead of signal, except when setting the handler to SIG_IGN or SIG_DFL
  #39: FILE: qemu-nbd.c:585:
  +    signal(SIGPIPE, foobar);

  total: 1 errors, 0 warnings, 10 lines checked

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>